server.port=8080
spring.application.name=nacosdemo
spring.profiles.active=dev



spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
spring.cloud.nacos.discovery.username=nacos
spring.cloud.nacos.discovery.password=nacos

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


spring.cloud.loadbalancer.ribbon.enabled=false
spring.cloud.loadbalancer.nacos.enabled=true

spring.cloud.nacos.server-addr=127.0.0.1:8848

spring.config.import=nacos:nacosdemo-dev.properties?refreshEnabled=true
spring.nacos.config.password=nacos
spring.nacos.config.username=nacos
spring.cloud.nacos.username=nacos
spring.cloud.nacos.password=nacos
